accountkit.settings:
  type: config_object
  label: 'Account Kit settings'
  mapping:
    app_id:
      type: string
      label: 'Application ID'
    app_secret:
      type: string
      label: 'App Secret'
    api_version:
      type: string
      label: 'Graph API version'
    redirect_url:
      type: string
      label: 'Redirect url'
    enable_email_auth:
      type: boolean
      label: 'Enable Email auth'
    enable_phone_auth:
      type: boolean
      label: 'Enable Phone auth'
